initial nttw4
MediaArea/MediaArea-Website pull request #249
Opened 2019-02-04 15:39 UTC by dericed

ping @JeromeMartinez @ablwr

2019-02-04 15:49 UTC, ablwr approved these changes
Looks ok to me but didn't test locally

2019-02-05 11:07 UTC, JeromeMartinez requested changes
I added the technical boilerplate.
+ some copy/paste fixes
But 1 missing info.

Please review my changes then squash in 1 commit.

2019-02-05 11:07 UTC, JeromeMartinez commented on src/NoTimeToWaitBundle/Resources/views/Default/nttw4.html.twig
> +<em>Photo Credit: <a href="">Vera and Donald Blinken Open Society Archives</a></em></p>
Bad copy/paste, I changed the credit name (please confirm it).
Do you have an URL for the credit?

2019-02-05 11:07 UTC, JeromeMartinez commented on src/NoTimeToWaitBundle/Resources/views/Default/index.html.twig
> +          Conferences used the tagline of:
I removed `both`, @dericed other suggestion?

2019-02-05 11:07 UTC, JeromeMartinez commented on src/NoTimeToWaitBundle/Resources/views/Default/nttw4.html.twig
> +<h2>Program</h2>
Bad copy/paste, I changed it.

2019-02-06 18:37 UTC, JeromeMartinez approved these changes

2019-02-06 18:43 UTC, merged