Nttw5 updates
MediaArea/MediaArea-Website pull request #374
Opened 2021-04-29 15:48 UTC by dericed

2021-04-29 16:06 UTC, retokromer commented on src/NoTimeToWaitBundle/Resources/views/Default/nttw5.html.twig
> +<p><i>Note: Due to the ongoing coronavirus (COVID-19) pandemic, No Time To Wait, which was originally scheduled for September 2020, had a series a postponements. As scientific and social progress con
nit: missing slash at closing tag `</p>`

2021-04-29 16:27 UTC, JeromeMartinez commented on src/NoTimeToWaitBundle/Resources/views/Default/nttw5.html.twig
> -<p>We continue to monitor the development and impact of the coronavirus and actively seek out health and safety guidance. If we can proceed with our plans safely, we hope that we can open the call fo
"September 2020", oops, good to remove this outdated expected date...

2021-04-29 16:48 UTC, JeromeMartinez requested changes

2021-04-29 16:48 UTC, JeromeMartinez commented on src/NoTimeToWaitBundle/Resources/views/Default/nttw5.html.twig
> +<p>We are currently developing a timeline to announce a call for proposals and open registration soon. To help us prepare for this, we request that you complete <a href="http://bit.ly/nttw5prelimsurv
The "What" title (see nttw4 page) disappeared in a previous patch, would be good to have it back.

![image](https://user-images.githubusercontent.com/1641638/116588084-6645e580-a91b-11eb-92c3-5f783827ff78.png)

2021-04-30 17:27 UTC, JeromeMartinez commented on src/NoTimeToWaitBundle/Resources/views/Default/nttw5.html.twig
> +<p><i>Note: Due to the ongoing coronavirus (COVID-19) pandemic, No Time To Wait, which was originally scheduled for September 2020, had a series a postponements. As scientific and social progress con
"a series a postponements" ?

2021-04-30 17:41 UTC, dericed commented on src/NoTimeToWaitBundle/Resources/views/Default/nttw5.html.twig
> +<p><i>Note: Due to the ongoing coronavirus (COVID-19) pandemic, No Time To Wait, which was originally scheduled for September 2020, had a series a postponements. As scientific and social progress con
fixed of `of`

2021-04-30 20:52 UTC, JeromeMartinez approved these changes

2021-05-01 04:26 UTC, retokromer approved these changes
Fingers crossed.

2021-05-03 13:11 UTC, merged